version: "3.8"

services:
  app:
    build: .
    image: tikhoplav/go
    volumes:
      - ./app:/app
      - ./pkg:/go/pkg
    ports:
      - 8080:8080
    environment:
      DB_URL: host=db port=5432 dbname=postgres user=postgres password=example

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: example